services:
  - type: web
    name: molino-rental-crm
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health-check
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000